name: Build Trakt Feed

on:
  schedule:
    - cron: '0 */2 * * *'  # Every two hours
  workflow_dispatch:

jobs:
  export-and-generate-feed:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install traktexport feedgen

      - name: Restore Traktexport credentials
        run: |
          mkdir -p ~/.local/share
          echo '${{ secrets.TRAKTEXPORT_AUTH }}' > ~/.local/share/traktexport.json

      - name: Export Trakt history
        run: traktexport partial_export davorg --pages 1 > history.json

      - name: Install cpanm
        run: |
          sudo apt-get update -y
          sudo apt-get install -y cpanminus 

      - name: Install modules
        run: cpanm --sudo --installdeps --notest .

      - name: Generate RSS feed
        run: |
          mkdir docs
          bin/mkfeed > docs/feed.xml

      - name: Upload RSS feed to Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

  deploy:
    needs: export-and-generate-feed
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

